services:
  - type: web
    name: binary-mlm-site
    env: node
    region: oregon
    plan: free
    repo: https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
